"use client";
import { useMemo } from "react";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { useTheme } from "@/components/theme-provider";

type SeriesPoint = { label: string; value: number; secondary?: number; discrepancy?: number };
type RiskPoint = { name: string; value: number; fill: string };
type TelemetryPoint = { label: string; risk: number; degradation: number; utilization: number; temperature?: number; vibration?: number };

export function UsageTrendChart({ data }: { data: SeriesPoint[] }) {
  const { theme } = useTheme(); const dark = theme === "dark";
  const colors = dark ? { grid: "rgba(148,163,184,.10)", text: "#718096", a: "#5eead4", b: "#60a5fa", tooltip: "#0d1219" } : { grid: "rgba(71,85,105,.12)", text: "#64748b", a: "#0f766e", b: "#2563eb", tooltip: "#ffffff" };
  return <ResponsiveContainer width="100%" height="100%"><AreaChart data={data} margin={{top:8,right:4,left:-18,bottom:0}}><defs><linearGradient id="usageFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor={colors.a} stopOpacity={.35}/><stop offset="100%" stopColor={colors.a} stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke={colors.grid} vertical={false}/><XAxis dataKey="label" tick={{fill:colors.text,fontSize:10}} axisLine={false} tickLine={false} minTickGap={18}/><YAxis tick={{fill:colors.text,fontSize:10}} axisLine={false} tickLine={false} width={30}/><Tooltip contentStyle={{backgroundColor:colors.tooltip,border:`1px solid ${colors.grid}`,borderRadius:5,color:dark?"#f8fafc":"#0f172a",fontSize:12}}/><Area type="monotone" dataKey="value" stroke={colors.a} strokeWidth={2.4} fill="url(#usageFill)" dot={false}/></AreaChart></ResponsiveContainer>
}

export function ComparisonTrendChart({ data }: { data: SeriesPoint[] }) {
  const { theme } = useTheme(); const dark = theme === "dark"; const c = dark ? {grid:"rgba(148,163,184,.10)",text:"#718096",counter:"#60a5fa",register:"#a7f3d0",bg:"#0d1219"} : {grid:"rgba(71,85,105,.12)",text:"#64748b",counter:"#2563eb",register:"#0f766e",bg:"#fff"};
  return <ResponsiveContainer width="100%" height="100%"><AreaChart data={data} margin={{top:8,right:4,left:-18,bottom:0}}><CartesianGrid stroke={c.grid} vertical={false}/><XAxis dataKey="label" tick={{fill:c.text,fontSize:10}} axisLine={false} tickLine={false} minTickGap={18}/><YAxis tick={{fill:c.text,fontSize:10}} axisLine={false} tickLine={false} width={30}/><Tooltip contentStyle={{backgroundColor:c.bg,border:`1px solid ${c.grid}`,borderRadius:5,color:dark?"#f8fafc":"#0f172a",fontSize:12}}/><Area type="monotone" dataKey="value" name="Counter" stroke={c.counter} fill={dark?"rgba(96,165,250,0.08)":"rgba(37,99,235,0.08)"} strokeWidth={2} dot={false}/><Area type="monotone" dataKey="secondary" name="Register" stroke={c.register} fill={dark?"rgba(167,243,208,0.05)":"rgba(15,118,110,0.06)"} strokeWidth={2} dot={false}/></AreaChart></ResponsiveContainer>
}

export function TelemetryRiskChart({ data }: { data: TelemetryPoint[] }) {
  const { theme } = useTheme(); const dark = theme === "dark"; const c = dark ? {grid:"rgba(148,163,184,.10)",text:"#718096",risk:"#f87171",deg:"#fb923c",util:"#60a5fa",bg:"#0d1219"} : {grid:"rgba(71,85,105,.12)",text:"#64748b",risk:"#dc2626",deg:"#c2410c",util:"#2563eb",bg:"#fff"};
  return <ResponsiveContainer width="100%" height="100%"><AreaChart data={data} margin={{top:8,right:4,left:-18,bottom:0}}><CartesianGrid stroke={c.grid} vertical={false}/><XAxis dataKey="label" tick={{fill:c.text,fontSize:10}} axisLine={false} tickLine={false} minTickGap={18}/><YAxis tick={{fill:c.text,fontSize:10}} axisLine={false} tickLine={false} width={30}/><Tooltip contentStyle={{backgroundColor:c.bg,border:`1px solid ${c.grid}`,borderRadius:5,color:dark?"#f8fafc":"#0f172a",fontSize:12}}/><Area type="monotone" dataKey="risk" name="Risk" stroke={c.risk} fill="rgba(248,113,113,0.06)" strokeWidth={2.2} dot={false}/><Area type="monotone" dataKey="utilization" name="Utilization %" stroke={c.util} fill="none" strokeWidth={1.8} dot={false}/><Area type="monotone" dataKey="degradation" name="Degradation" stroke={c.deg} fill="none" strokeWidth={1.8} dot={false}/></AreaChart></ResponsiveContainer>
}

export function RiskDonut({ data }: { data: RiskPoint[] }) { const { theme } = useTheme(); const dark = theme === "dark"; const valid=data.filter(d=>d.value>0); const total=valid.reduce((s,d)=>s+d.value,0); return <ResponsiveContainer width="100%" height="100%" minWidth={170} minHeight={170}><PieChart margin={{top:6,right:6,bottom:6,left:6}}><Pie data={valid} dataKey="value" nameKey="name" innerRadius="55%" outerRadius="80%" startAngle={90} endAngle={-270} paddingAngle={valid.length>1?2:0} stroke="none" isAnimationActive animationBegin={120} animationDuration={700}>{valid.map(i=><Cell key={i.name} fill={i.fill}/>)}</Pie><text x="50%" y="47%" textAnchor="middle" dominantBaseline="middle" fill={dark?"#f8fafc":"#0f172a"} fontSize="20" fontWeight="700">{total}</text><text x="50%" y="59%" textAnchor="middle" dominantBaseline="middle" fill={dark?"#718096":"#64748b"} fontSize="9">ASSETS</text><Tooltip contentStyle={{backgroundColor:dark?"#0d1219":"#fff",border:`1px solid ${dark?"rgba(255,255,255,.09)":"rgba(15,23,42,.12)"}`,borderRadius:5,color:dark?"#f8fafc":"#0f172a",fontSize:12}}/></PieChart></ResponsiveContainer> }

export function RiskBars({ data }: { data: SeriesPoint[] }) { const { theme }=useTheme(); const dark=theme==="dark"; const c=dark?{grid:"rgba(148,163,184,.08)",text:"#718096",bar:"#60a5fa",bg:"#0d1219"}:{grid:"rgba(71,85,105,.12)",text:"#64748b",bar:"#2563eb",bg:"#fff"}; return <ResponsiveContainer width="100%" height="100%"><BarChart data={data} margin={{top:8,right:4,left:-18,bottom:0}}><CartesianGrid stroke={c.grid} vertical={false}/><XAxis dataKey="label" tick={{fill:c.text,fontSize:10}} axisLine={false} tickLine={false}/><YAxis tick={{fill:c.text,fontSize:10}} axisLine={false} tickLine={false} width={30}/><Tooltip contentStyle={{backgroundColor:c.bg,border:`1px solid ${c.grid}`,borderRadius:5,color:dark?"#f8fafc":"#0f172a",fontSize:12}}/><Bar dataKey="value" fill={c.bar} radius={[5,5,2,2]} maxBarSize={26} isAnimationActive animationDuration={650}/></BarChart></ResponsiveContainer> }
