import { notFound } from "next/navigation";
import Link from "next/link";
import { ArrowLeft, ArrowUpRight, CalendarClock, CheckCircle2, CircleAlert, Factory, Gauge, Wrench } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { StatusBadge } from "@/components/ui/status-badge";
import { Reveal } from "@/components/dashboard/motion";
import { ComparisonTrendChart } from "@/components/dashboard/charts";
import { TelemetryInsights } from "@/components/dashboard/telemetry-insights";
import { TechnicianLog } from "@/components/dashboard/technician-log";
import { EquipmentActions } from "@/components/dashboard/equipment-actions";
import { getEquipmentById, getAlertsForEquipment, getFacilityById, getEquipmentTrend, formatEquipmentType, getEquipmentHealthScore, getRiskDrivers, getFailureSummary } from "@/lib/data/insights";

export default async function EquipmentDetailPage({ params }: { params: Promise<{ equipmentId: string }> }){
 const {equipmentId}=await params; const found=getEquipmentById(equipmentId); if(!found) notFound(); const item=found; const facility=getFacilityById(item.facilityId); const alerts=getAlertsForEquipment(item.id); if(!facility) notFound(); const trend=getEquipmentTrend(item);
 return <div className="space-y-5">
  <Reveal><Link href="/equipment" className="inline-flex items-center gap-2 text-xs font-semibold text-slate-500 hover:text-white"><ArrowLeft className="h-3.5 w-3.5"/> Back to equipment</Link><div className="mt-4 flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><div className="flex flex-wrap items-center gap-2"><StatusBadge level={item.riskLevel}/><span className="rounded-[5px] border border-white/[0.07] bg-white/[0.025] px-2.5 py-1 text-[10px] font-medium text-slate-500">{formatEquipmentType(item.type)}</span></div><h1 className="mt-3 text-3xl font-semibold tracking-tight text-white">{item.name}</h1><p className="mt-2 text-sm text-slate-500">{facility?.name} · {facility?.county} · {item.serialNumber}</p></div><div className="flex flex-wrap items-end gap-3"><EquipmentActions equipment={item} facility={facility} alert={alerts[0]}/><div className="rounded-[5px] border border-red-400/15 bg-red-400/[0.05] px-5 py-4"><p className="text-[10px] uppercase tracking-[0.18em] text-red-300">Predicted failure window</p><p className="mt-1 text-2xl font-semibold text-white">{item.leadTimeDays} <span className="text-sm font-normal text-slate-500">usage-days</span></p></div></div></div></Reveal>
  <section className="grid gap-4 xl:grid-cols-[1.65fr_1fr]"><Reveal delay={0.08}><Card className="h-[380px] border-white/[0.07] bg-white/[0.025] ring-0"><CardHeader className="border-b border-white/[0.06] pb-4"><div className="flex items-center justify-between"><div><CardTitle className="text-sm font-semibold text-white">Usage history</CardTitle><p className="mt-1 text-xs text-slate-500">Equipment counter against registered activity.</p></div><span className="text-[10px] uppercase tracking-[0.15em] text-slate-600">Last 10 records</span></div></CardHeader><CardContent className="h-[300px] pt-5"><ComparisonTrendChart data={trend}/></CardContent></Card></Reveal>
   <Reveal delay={0.12}><Card className="border-white/[0.07] bg-white/[0.025] ring-0"><CardHeader className="border-b border-white/[0.06] pb-4"><CardTitle className="text-sm font-semibold text-white">Risk intelligence</CardTitle><p className="mt-1 text-xs text-slate-500">Why this asset is being prioritized.</p></CardHeader><CardContent className="space-y-5 p-5"><div><div className="flex items-end justify-between"><span className="text-xs text-slate-500">Risk score</span><span className="text-2xl font-semibold text-white">{item.riskScore}<span className="text-xs font-normal text-slate-600">/100</span></span></div><div className="mt-3 h-2 overflow-hidden rounded-[5px] bg-white/[0.06]"><div className="h-full rounded-[5px] bg-gradient-to-r from-amber-300 to-red-400" style={{width:`${item.riskScore}%`}}/></div></div><div className="grid grid-cols-2 gap-3"><div className="rounded-[5px] border border-white/[0.06] bg-white/[0.02] p-3"><p className="text-[9px] uppercase tracking-[0.15em] text-slate-600">Counter</p><p className="mt-1 text-lg font-semibold text-slate-200">{item.counterUsage}</p></div><div className="rounded-[5px] border border-white/[0.06] bg-white/[0.02] p-3"><p className="text-[9px] uppercase tracking-[0.15em] text-slate-600">Register</p><p className="mt-1 text-lg font-semibold text-slate-200">{item.registerUsage}</p></div></div><div className="rounded-[5px] border border-orange-400/10 bg-orange-400/[0.045] p-4"><div className="flex gap-3"><CircleAlert className="mt-0.5 h-4 w-4 text-orange-300"/><div><p className="text-xs font-semibold text-orange-200">Risk rationale</p><p className="mt-1 text-[11px] leading-5 text-slate-500">{item.scenarioRationale}</p></div></div></div></CardContent></Card></Reveal>
  </section>
  <Reveal delay={0.14}><div className="grid gap-4 lg:grid-cols-[1.1fr_0.9fr]">
    <Card className="border-white/[0.07] bg-white/[0.025] ring-0"><CardHeader className="border-b border-white/[0.06] pb-4"><CardTitle className="text-sm font-semibold text-white">Equipment health score</CardTitle><p className="mt-1 text-xs text-slate-500">Composite view of reliability, maintenance, utilization and reporting integrity.</p></CardHeader><CardContent className="space-y-4 p-5"><div className="flex items-end justify-between"><div><p className="text-[9px] uppercase tracking-[0.15em] text-slate-500">Overall health</p><p className="mt-1 text-3xl font-semibold text-foreground">{getEquipmentHealthScore(item).overall}<span className="text-sm font-normal text-slate-500">/100</span></p></div><StatusBadge level={getEquipmentHealthScore(item).overall<45?"critical":getEquipmentHealthScore(item).overall<65?"high":"low"}/></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{Object.entries(getEquipmentHealthScore(item)).filter(([k])=>k!=="overall").map(([key,value])=><div key={key} className="rounded-[5px] border border-white/[0.06] bg-white/[0.02] p-3"><p className="text-[9px] uppercase tracking-[0.12em] text-slate-500">{key}</p><p className="mt-1 text-lg font-semibold">{value}</p></div>)}</div><div className="rounded-[5px] border border-blue-400/10 bg-blue-400/[0.035] p-4"><p className="text-xs font-semibold text-blue-700 dark:text-blue-300">Why this asset is risky</p><div className="mt-3 space-y-2">{getRiskDrivers(item).map(driver=><div key={driver.label} className="flex items-center gap-3"><span className="w-36 truncate text-[10px] text-slate-500">{driver.label}</span><div className="h-1.5 flex-1 overflow-hidden rounded-[5px] bg-slate-200 dark:bg-white/[0.06]"><div className="h-full rounded-[5px] bg-blue-500" style={{width:`${Math.min(100,driver.value*4)}%`}}/></div><span className="w-7 text-right text-[10px] font-semibold">{driver.value}</span></div>)}</div></div></CardContent></Card>
    <Card className="border-white/[0.07] bg-white/[0.025] ring-0"><CardHeader className="border-b border-white/[0.06] pb-4"><CardTitle className="text-sm font-semibold text-white">Failure exposure</CardTitle><p className="mt-1 text-xs text-slate-500">Historical failure-event impact from the backend dataset.</p></CardHeader><CardContent className="grid grid-cols-2 gap-3 p-5"><div className="rounded-[5px] border border-white/[0.06] bg-white/[0.02] p-4"><p className="text-[9px] uppercase tracking-[0.14em] text-slate-500">Events</p><p className="mt-1 text-2xl font-semibold">{getFailureSummary(item).count}</p></div><div className="rounded-[5px] border border-white/[0.06] bg-white/[0.02] p-4"><p className="text-[9px] uppercase tracking-[0.14em] text-slate-500">Downtime</p><p className="mt-1 text-2xl font-semibold">{getFailureSummary(item).downtimeHours}h</p></div><div className="col-span-2 rounded-[5px] border border-amber-400/10 bg-amber-400/[0.03] p-4"><p className="text-[9px] uppercase tracking-[0.14em] text-amber-700 dark:text-amber-300">Estimated repair exposure</p><p className="mt-1 text-xl font-semibold">KSh {Math.round(getFailureSummary(item).repairCost).toLocaleString()}</p><p className="mt-1 text-[10px] text-slate-500">Derived from recorded failure-event estimates.</p></div></CardContent></Card>
  </div></Reveal>
  <Reveal delay={0.18}><TelemetryInsights equipment={item}/></Reveal>
  <section className="grid gap-4 lg:grid-cols-[1fr_1.25fr]"><Reveal delay={0.16}><Card className="border-white/[0.07] bg-white/[0.025] ring-0"><CardHeader className="border-b border-white/[0.06] pb-4"><CardTitle className="text-sm font-semibold text-white">Asset metadata</CardTitle></CardHeader><CardContent className="grid grid-cols-2 gap-4 p-5"><div><p className="text-[9px] uppercase tracking-[0.15em] text-slate-600">Install date</p><p className="mt-1 text-xs text-slate-300">{item.installDate}</p></div><div><p className="text-[9px] uppercase tracking-[0.15em] text-slate-600">Last maintenance</p><p className="mt-1 text-xs text-slate-300">{item.lastMaintenanceDate}</p></div><div><p className="text-[9px] uppercase tracking-[0.15em] text-slate-600">Usage days</p><p className="mt-1 text-xs text-slate-300">{item.usageDays.toLocaleString()}</p></div><div><p className="text-[9px] uppercase tracking-[0.15em] text-slate-600">Discrepancy</p><p className="mt-1 text-xs text-slate-300">{item.discrepancyPercent}%</p></div></CardContent></Card></Reveal><Reveal delay={0.2}><Card className="border-white/[0.07] bg-white/[0.025] ring-0"><CardHeader className="border-b border-white/[0.06] pb-4"><div className="flex items-center justify-between"><div><CardTitle className="text-sm font-semibold text-white">Maintenance timeline</CardTitle><p className="mt-1 text-xs text-slate-500">Recent biomedical engineering activity.</p></div><Wrench className="h-4 w-4 text-slate-600"/></div></CardHeader><CardContent className="p-5"><div className="space-y-4">{item.maintenanceLog.slice().reverse().map(record=><div key={record.id} className="flex gap-3"><div className="mt-1 flex h-7 w-7 shrink-0 items-center justify-center rounded-[5px] bg-white/[0.04] text-blue-300"><Wrench className="h-3.5 w-3.5"/></div><div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-3"><p className="text-xs font-semibold capitalize text-slate-300">{record.type}</p><span className="text-[10px] text-slate-600">{record.date}</span></div><p className="mt-1 text-[11px] leading-5 text-slate-500">{record.notes}</p></div></div>)}</div></CardContent></Card></Reveal></section>
  <Reveal delay={0.24}><TechnicianLog equipment={item}/></Reveal>{alerts.length>0&&<Reveal delay={0.28}><Card className="border-red-400/10 bg-red-400/[0.025] ring-0"><CardHeader><div className="flex items-center gap-2"><CircleAlert className="h-4 w-4 text-red-300"/><CardTitle className="text-sm font-semibold text-white">Open signals for this asset</CardTitle></div></CardHeader><CardContent className="space-y-2">{alerts.map(alert=><div key={alert.id} className="rounded-[5px] border border-white/[0.06] bg-black/10 p-4"><div className="flex items-center justify-between gap-3"><p className="text-xs font-semibold text-slate-300">{alert.message}</p><span className="text-[9px] uppercase tracking-[0.15em] text-red-300">{alert.severity}</span></div></div>)}</CardContent></Card></Reveal>}
 </div>;
}
