import Link from "next/link";
import { ArrowLeft, ArrowUpRight, Building2, Gauge, MapPin, ShieldCheck, Wrench } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { StatusBadge } from "@/components/ui/status-badge";
import { Reveal } from "@/components/dashboard/motion";
import { RiskDonut } from "@/components/dashboard/charts";
import { getFacilitySummary, getFacilityEligibilitySummary, formatEquipmentType } from "@/lib/data/insights";
import { notFound } from "next/navigation";

export default async function FacilityDetailPage({ params }: { params: Promise<{ facilityId: string }> }) {
  const { facilityId } = await params; const summary = getFacilitySummary(facilityId); if (!summary.facility) notFound();
  const risk = { critical:summary.equipment.filter(e=>e.riskLevel==='critical').length, high:summary.equipment.filter(e=>e.riskLevel==='high').length, medium:summary.equipment.filter(e=>e.riskLevel==='medium').length, low:summary.equipment.filter(e=>e.riskLevel==='low').length };
  const donut=[{name:'Critical',value:risk.critical,fill:'#f87171'},{name:'High',value:risk.high,fill:'#fb923c'},{name:'Moderate',value:risk.medium,fill:'#fbbf24'},{name:'Low',value:risk.low,fill:'#34d399'}];
  const eligibility=getFacilityEligibilitySummary(summary.facility);
  return <div className="space-y-5">
    <Reveal><Link href="/facilities" className="inline-flex items-center gap-2 text-xs font-semibold text-slate-500 hover:text-foreground"><ArrowLeft className="h-3.5 w-3.5"/> Back to facilities</Link><div className="mt-4 flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-[10px] font-semibold uppercase tracking-[0.2em] text-blue-600 dark:text-blue-300">Facility intelligence</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">{summary.facility.name}</h1><p className="mt-2 flex items-center gap-2 text-sm text-slate-500"><MapPin className="h-3.5 w-3.5"/>{summary.facility.county} · {summary.facility.serviceLevel.replace("Level ","Level ")} · {summary.facility.facilityType}</p></div><div className="flex items-center gap-2 rounded-[5px] border border-white/[0.07] bg-white/[0.025] px-4 py-3"><Gauge className="h-4 w-4 text-blue-500"/><div><p className="text-[9px] uppercase tracking-[0.16em] text-slate-500">Average risk</p><p className="text-lg font-semibold">{summary.riskScore}<span className="text-xs font-normal text-slate-500">/100</span></p></div></div></div></Reveal>
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Reveal><Card className="ring-0"><CardContent className="p-4"><p className="text-[9px] uppercase tracking-[0.15em] text-slate-500">Capacity</p><p className="mt-1 text-xl font-semibold">{(summary.facility.bedsAndCots ?? 0).toLocaleString()}</p><p className="text-[10px] text-slate-500">beds + cots</p></CardContent></Card></Reveal><Reveal delay={.04}><Card className="ring-0"><CardContent className="p-4"><p className="text-[9px] uppercase tracking-[0.15em] text-slate-500">Utilization</p><p className="mt-1 text-xl font-semibold">{Math.round(summary.utilization*100)}%</p><p className="text-[10px] text-slate-500">latest monitored assets</p></CardContent></Card></Reveal><Reveal delay={.08}><Card className="ring-0"><CardContent className="p-4"><p className="text-[9px] uppercase tracking-[0.15em] text-slate-500">Downtime</p><p className="mt-1 text-xl font-semibold">{summary.downtime.toFixed(1)}h</p><p className="text-[10px] text-slate-500">recorded failure downtime</p></CardContent></Card></Reveal><Reveal delay={.12}><Card className="ring-0"><CardContent className="p-4"><p className="text-[9px] uppercase tracking-[0.15em] text-slate-500">Owner type</p><p className="mt-1 truncate text-sm font-semibold">{summary.facility.ownerType || "Not recorded"}</p><p className="text-[10px] text-slate-500">facility master</p></CardContent></Card></Reveal></section>
    <section className="grid gap-4 xl:grid-cols-[1.4fr_.85fr]"><Reveal delay={.12}><Card className="ring-0"><CardHeader className="border-b pb-4"><CardTitle className="text-sm font-semibold">Equipment portfolio</CardTitle><p className="mt-1 text-xs text-slate-500">Assets currently monitored at this facility.</p></CardHeader><CardContent className="p-0"><div className="divide-y">{summary.equipment.length?summary.equipment.map(item=><Link key={item.id} href={`/equipment/${item.id}`} className="flex items-center gap-4 px-5 py-4 hover:bg-black/[0.02] dark:hover:bg-white/[0.025]"><div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-[5px] bg-blue-500/[0.06] text-blue-600 dark:text-blue-300"><Building2 className="h-4 w-4"/></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="truncate text-sm font-semibold">{item.name}</p><StatusBadge level={item.riskLevel}/></div><p className="mt-1 text-xs text-slate-500">{formatEquipmentType(item.type)} · {item.serialNumber}</p></div><div className="text-right"><p className="text-sm font-semibold">{item.riskScore}</p><p className="text-[9px] uppercase tracking-[0.15em] text-slate-500">risk</p></div><ArrowUpRight className="h-3.5 w-3.5 text-slate-400"/></Link>):<div className="p-6 text-sm text-slate-500">No monitored equipment is attached to this facility.</div>}</div></CardContent></Card></Reveal><Reveal delay={.16}><Card className="ring-0"><CardHeader className="border-b pb-4"><CardTitle className="text-sm font-semibold">Risk profile</CardTitle><p className="mt-1 text-xs text-slate-500">Current distribution across monitored assets.</p></CardHeader><CardContent><div className="mx-auto h-56 max-w-[260px]"><RiskDonut data={donut}/></div><div className="grid grid-cols-2 gap-3">{Object.entries(risk).map(([key,value])=><div key={key} className="rounded-[5px] border border-white/[0.06] bg-white/[0.02] p-3"><p className="text-[9px] uppercase tracking-[0.15em] text-slate-500">{key}</p><p className="mt-1 text-lg font-semibold">{value}</p></div>)}</div></CardContent></Card></Reveal></section>
    <section className="grid gap-4 lg:grid-cols-2"><Reveal delay={.2}><Card className="ring-0"><CardHeader className="border-b pb-4"><div className="flex items-center gap-2"><ShieldCheck className="h-4 w-4 text-emerald-500"/><div><CardTitle className="text-sm font-semibold">Equipment eligibility</CardTitle><p className="mt-1 text-xs text-slate-500">Eligibility flags supplied by the facility master.</p></div></div></CardHeader><CardContent className="grid grid-cols-2 gap-3 p-5">{eligibility.map(item=><div key={item.label} className="flex items-center justify-between rounded-[5px] border border-white/[0.06] bg-white/[0.02] px-3 py-2.5"><span className="text-[10px] text-slate-500">{item.label}</span><span className={item.eligible===true?"text-[10px] font-semibold text-emerald-600 dark:text-emerald-300":item.eligible===false?"text-[10px] font-semibold text-slate-400":"text-[10px] font-semibold text-amber-600 dark:text-amber-300"}>{item.eligible===true?"Eligible":item.eligible===false?"Not eligible":"Unknown"}</span></div>)}</CardContent></Card></Reveal><Reveal delay={.24}><Card className="ring-0"><CardHeader className="border-b pb-4"><div className="flex items-center gap-2"><Wrench className="h-4 w-4 text-blue-500"/><div><CardTitle className="text-sm font-semibold">Facility operations</CardTitle><p className="mt-1 text-xs text-slate-500">Availability and master-record context.</p></div></div></CardHeader><CardContent className="grid grid-cols-2 gap-3 p-5">{[['Operation',summary.facility.operationStatus],['Whole day',summary.facility.openWholeDay],['Weekends',summary.facility.openWeekends],['Late night',summary.facility.openLateNight],['Sub-county',summary.facility.subCounty],['Ward',summary.facility.ward]].map(([k,v])=><div key={k} className="rounded-[5px] border border-white/[0.06] bg-white/[0.02] p-3"><p className="text-[9px] uppercase tracking-[0.14em] text-slate-500">{k}</p><p className="mt-1 truncate text-xs font-semibold">{v || 'Not recorded'}</p></div>)}</CardContent></Card></Reveal></section>
  </div>
}
